channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - numpy=1.26
  - python=3.11
  - pip:
      - geopandas==0.14
      - matplotlib==3.8
      - matplotlib-inline==0.1
      - mesa==2.1
      - mesa-geo==0.7
      - mesa-viz-tornado==0.1
      - networkx==3.2
      - pandas==2.2.0
      - rasterio==1.3
      - scikit-learn==1.4
      - scipy==1.12
      - seaborn==0.13
      - shapely==2.0
      - statsmodels==0.14